import * as _ from 'lodash';

const localUrl = 'localhost';
const devUrl = 'dvmka047.dev.sprint.com';

const DB_URL_COMPLEMENT = [
  {
    URL: localUrl,
    APPID: 'REL',
    Env: 'DEV',
    PORT: '8080'
  },
  {
    URL: devUrl,
    APPID: 'REL',
    Env: 'PROD',
    PORT: '8099'
  }
];

const DB_DETAILS = [
  {
    DEV: {
      DEV1: { rhs: 'RHSD101', lfo: 'RSKD101', vwi: 'PRTD101', rai: 'TELD101', ra: null },
      DEV2: { rhs: 'RHSD201', lfo: 'RSKD201', vwi: 'PRTD201', rai: 'TELD201', ra: null },
      DEV3: { rhs: 'RHSD301', lfo: 'RSKD301', vwi: 'PRTD301', rai: 'TELD301', ra: null },
      DEV4: { rhs: 'RHSD401', lfo: 'RSKD401', vwi: 'PRTD401', rai: 'TELD401', ra: null },
      DEV5: { rhs: 'RHSD501', lfo: 'RSKD501', vwi: 'PRTD501', rai: 'TELD501', ra: null },
      DEV6: { rhs: 'RHSD601', lfo: 'RSKD601', vwi: 'PRTD601', rai: 'TELD601', ra: null },
      DEV7: { rhs: 'RHSD701', lfo: 'RSKD701', vwi: 'PRTD701', rai: 'TELD701', ra: null },
      DEV8: { rhs: 'RHSD801', lfo: 'RSKD801', vwi: 'PRTD801', rai: 'TELD801', ra: null },
      DEV9: { rhs: 'RHSD901', lfo: 'RSKD901', vwi: 'PRTD901', rai: 'TELD901', ra: null },
      DEV10: { rhs: 'RHSD001', lfo: 'RSKD001', vwi: 'PRTD001', rai: 'TELD001', ra: null },
      DEV01: { rhs: null, lfo: null, vwi: null, rai: null, ra: 'drhrx1_dev01' }
    }
  },
  {
    TEST: {
      ITE1: { rhs: 'RMST101', lfo: 'RSKT101', vwi: 'PRTT101', rai: 'TELT101', ra: null },
      ITE2: { rhs: 'RMST201', lfo: 'RSKT201', vwi: 'PRTT201', rai: 'TELT201', ra: null },
      ITE3: { rhs: 'RMST401', lfo: 'RSKT301', vwi: 'PRTT104', rai: 'TELT401', ra: null },
      QLAB01: { rhs: null, lfo: null, vwi: null, rai: null, ra: 'qrhrx1_qat01' }
    }
  }
];

const URL_DETAILS = {
  fo: '/rmsfo/RmsSpring/LoginController/launchLoginPage',
  ws: '/rms/RmsService?wsdl',
  bo: '/retailservices/dist/',
  es: '/RmsRestService/startUpService/loadStartUpData?appId=RHS&appPassword=RMSBO',
  drLogin: '/rmsfo/controller/AuthenticationConversation/byPassAuthentication?username=RASHMI&locId=8&pwd=SPRINT01&userId=12460793',
  dr: '/rmsfo/controller/ClearSessionReplyConversation/doApplicationDataReload?reload=1&url=/config/retailservices.properties',
  wsReload: '/rms/rmswsdatareload',
  jm: '/rms/RmsSymmetricService?wsdl'
};

const SERVER_DETAILS = [
  { db: 'RHSD101', foLog:'/logs/rhs/development1/jboss/dvmka433/rhs-development1-rms1/AppLog/', wsLog: '/logs/rhs/development1/jboss/dvmka433/rhs-development1-rms1/WebSrv/AppLog/', boLog: '/logs/rhs/development0/jboss/dvmki811/rhs-development0-rmsmodern/RearchLog/', jmLog: '/logs/ws2/development1/jboss/dvmki489/ws2-development1-rcdws/rhs/production/apps/', foHost: 'dvmka433.dev.sprint.com', jmHost: 'dvmki489.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8180', boPort: '8080', jmPort: '8180', esPort: '12080', displayName: 'RHS DEV1', tns: ['RHSD101=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(COMMUNITY=TCP.WORLD)(PROTOCOL=TCP)(HOST=DREAA658.DEV.SPRINT.COM)(PORT=1525)))(CONNECT_DATA=(SID=RHSD101)))', 'CNTD101=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=dreab485.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTD1APPS)))'] },
  { db: 'RHSD201', foLog:'/logs/rhs/development2/jboss/dvmka433/rhs-development2-rms1/AppLog/', wsLog: '/logs/rhs/development2/jboss/dvmka433/rhs-development2-rms1/WebSrv/AppLog/', boLog: '/logs/rhs/development1/jboss/dvmki811/rhs-development1-rmsmodern/RearchLog/', jmLog: '/logs/ws2/development2/jboss/dvmki489/ws2-development2-rcdws/rhs/production/apps/', foHost: 'dvmka433.dev.sprint.com', jmHost: 'dvmki489.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8280', boPort: '8180', jmPort: '8280', esPort: '12180', displayName: 'RHS DEV2', tns: ['RHSD201=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(COMMUNITY=TCP.WORLD)(PROTOCOL=TCP)(HOST=DREAA658.DEV.SPRINT.COM)(PORT=1525)))(CONNECT_DATA=(SID=RHSD201)))', 'CNTD201=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=dreab485.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTD2APPS)))'] },
  { db: 'RHSD301', foLog:'/logs/rhs/development3/jboss/dvmka433/rhs-development3-rms1/AppLog/', wsLog: '/logs/rhs/development3/jboss/dvmka433/rhs-development3-rms1/WebSrv/AppLog/', boLog: '/logs/rhs/development2/jboss/dvmki811/rhs-development2-rmsmodern/RearchLog/', jmLog: '/logs/ws2/development3/jboss/dvmki489/ws2-development3-rcdws/rhs/production/apps/', foHost: 'dvmka433.dev.sprint.com', jmHost: 'dvmki489.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8380', boPort: '8280', jmPort: '8380', esPort: '12280', displayName: 'RHS DEV3', tns: ['RHSD301=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(COMMUNITY=TCP.WORLD)(PROTOCOL=TCP)(HOST=DREAA658.DEV.SPRINT.COM)(PORT=1525)))(CONNECT_DATA=(SID=RHSD301)))', 'CNTD301=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=dreab485.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTD3APPS)))'] },
  { db: 'RHSD401', foLog:'/logs/rhs/development4/jboss/dvmka433/rhs-development4-rms1/AppLog/', wsLog: '/logs/rhs/development4/jboss/dvmka433/rhs-development4-rms1/WebSrv/AppLog/', boLog: '/logs/rhs/development3/jboss/dvmki811/rhs-development3-rmsmodern/RearchLog/', jmLog: '/logs/ws2/development4/jboss/dvmki489/ws2-development4-rcdws/rhs/production/apps/', foHost: 'dvmka433.dev.sprint.com', jmHost: 'dvmki489.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8480', boPort: '8380', jmPort: '8480', esPort: '12380', displayName: 'RHS DEV4', tns: ['RHSD401=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(COMMUNITY=TCP.WORLD)(PROTOCOL=TCP)(HOST=DREAA658.DEV.SPRINT.COM)(PORT=1525)))(CONNECT_DATA=(SID=RHSD401)))', 'CNTD401=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=dreab485.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTD4APPS)))'] },
  { db: 'RHSD501', foLog:'/logs/rhs/development5/jboss/dvmka433/rhs-development5-rms1/AppLog/', wsLog: '/logs/rhs/development5/jboss/dvmka433/rhs-development5-rms1/WebSrv/AppLog/', boLog: '/logs/rhs/development4/jboss/dvmki811/rhs-development4-rmsmodern/RearchLog/', jmLog: '/logs/ws2/development5/jboss/dvmki489/ws2-development5-rcdws/rhs/production/apps/', foHost: 'dvmka433.dev.sprint.com', jmHost: 'dvmki489.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8580', boPort: '8480', jmPort: '8580', esPort: '12480', displayName: 'RHS DEV5', tns: ['RHSD501=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(COMMUNITY=TCP.WORLD)(PROTOCOL=TCP)(HOST=DREAA658.DEV.SPRINT.COM)(PORT=1525)))(CONNECT_DATA=(SID=RHSD501)))', 'CNTD501=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=dreab485.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTD5APPS)))'] },
  { db: 'RHSD601', foLog:'/logs/rhs/development6/jboss/dvmka433/rhs-development6-rms1/AppLog/', wsLog: '/logs/rhs/development6/jboss/dvmka433/rhs-development6-rms1/WebSrv/AppLog/', boLog: '/logs/rhs/development5/jboss/dvmki811/rhs-development5-rmsmodern/RearchLog/', jmLog: '/logs/ws2/development6/jboss/dvmki489/ws2-development6-rcdws/rhs/production/apps/', foHost: 'dvmka433.dev.sprint.com', jmHost: 'dvmki489.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '9580', boPort: '8580', jmPort: '8680', esPort: '12580', displayName: 'RHS DEV6', tns: ['RHSD601=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=dreaa658.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=RHSD601)))', 'CNTD601=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=dreab485.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTD6APPS)))'] },
  { db: 'RHSD701', foLog:'/logs/rhs/development7/jboss/dvmka433/rhs-development7-rms1/AppLog/', wsLog: '/logs/rhs/development7/jboss/dvmka433/rhs-development7-rms1/WebSrv/AppLog/', boLog: '/logs/rhs/development6/jboss/dvmki811/rhs-development6-rmsmodern/RearchLog/', jmLog: '/logs/ws2/development7/jboss/dvmki489/ws2-development7-rcdws/rhs/production/apps/', foHost: 'dvmka433.dev.sprint.com', jmHost: 'dvmki489.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '9680', boPort: '8680', jmPort: '8780', esPort: '12680', displayName: 'RHS DEV7', tns: ['RHSD701=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=dreaa658.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=RHSD701)))', 'CNTD701=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=dreab485.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTD7APPS)))'] },
  { db: 'RHSD801', foLog:'/logs/rhs/development8/jboss/dvmka433/rhs-development8-rms1/AppLog/', wsLog: '/logs/rhs/development8/jboss/dvmka433/rhs-development8-rms1/WebSrv/AppLog/', boLog: '/logs/rhs/development7/jboss/dvmki811/rhs-development7-rmsmodern/RearchLog/', jmLog: '/logs/ws2/development8/jboss/dvmki489/ws2-development8-rcdws/rhs/production/apps/', foHost: 'dvmka433.dev.sprint.com', jmHost: 'dvmki489.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '9780', boPort: '8780', jmPort: '8880', esPort: '12780', displayName: 'RHS DEV8', tns: ['RHSD801=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=dreaa658.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=RHSD801)))', 'CNTD801=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=dreab485.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTD8APPS)))'] },
  { db: 'RHSD901', foLog:'/logs/rhs/development9/jboss/dvmka433/rhs-development9-rms1/AppLog/', wsLog: '/logs/rhs/development9/jboss/dvmka433/rhs-development9-rms1/WebSrv/AppLog/', boLog: '/logs/rhs/development8/jboss/dvmki811/rhs-development8-rmsmodern/RearchLog/', jmLog: '/logs/ws2/development9/jboss/dvmki489/ws2-development9-rcdws/rhs/production/apps/', foHost: 'dvmka433.dev.sprint.com', jmHost: 'dvmki489.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '9880', boPort: '8880', jmPort: '8980', esPort: '12880', displayName: 'RHS DEV9', tns: ['RHSD901=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=dreaa658.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=RHSD901)))', 'CNTD901=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=dreab485.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTD9APPS)))'] },
  { db: 'RHSD001', foLog:'/logs/rhs/development10/jboss/dvmka433/rhs-development10-rms1/AppLog/', wsLog: '/logs/rhs/development10/jboss/dvmka433/rhs-development10-rms1/WebSrv/AppLog/', boLog: '/logs/rhs/development9/jboss/dvmki811/rhs-development9-rmsmodern/RearchLog/', jmLog: '/logs/ws2/development10/jboss/dvmki489/ws2-development10-rcdws/rhs/production/apps/', foHost: 'dvmka433.dev.sprint.com', jmHost: 'dvmki489.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '9980', boPort: '8980', jmPort: '9080', esPort: '12980', displayName: 'RHS DEV10', tns: ['RHSD001=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(COMMUNITY=TCP.WORLD)(PROTOCOL=TCP)(HOST=DREAA658.DEV.SPRINT.COM)(PORT=1525)))(CONNECT_DATA=(SID=RHSD001)))', 'CNTD001=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=dreab485.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTD0APPS)))'] },
  { db: 'PRTD101', foLog:'/logs/vwi/development1/jboss/dvmka433/vwi-development1-rms1/AppLog/', wsLog: '/logs/vwi/development1/jboss/dvmka433/vwi-development1-rms1/WebSrv/AppLog/', boLog: '/logs/vwi/development0/jboss/dvmki811/vwi-development0-rmsmodern/RearchLog/', foHost: 'dvmka433.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '9080', boPort: '9080', esPort: '13080', displayName: 'VWI DEV1', tns: ['PRTD101=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(COMMUNITY=TCP.WORLD)(PROTOCOL=TCP)(HOST=DREAA658.DEV.SPRINT.COM)(PORT=1525)))(CONNECT_DATA=(SERVICE_NAME=PRTD101)))'] },
  { db: 'PRTD201', foLog:'/logs/vwi/development2/jboss/dvmka433/vwi-development1-rms2/AppLog/', wsLog: '/logs/vwi/development2/jboss/dvmka433/vwi-development1-rms2/WebSrv/AppLog/', boLog: '/logs/vwi/development1/jboss/dvmki811/vwi-development1-rmsmodern/RearchLog/', foHost: 'dvmka433.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '9180', boPort: '9180', esPort: '13180', displayName: 'VWI DEV2', tns: ['PRTD201=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(COMMUNITY=TCP.WORLD)(PROTOCOL=TCP)(HOST=DREAA658.DEV.SPRINT.COM)(PORT=1525)))(CONNECT_DATA=(SERVICE_NAME=PRTD201)))'] },
  { db: 'PRTD301', foLog:'/logs/vwi/development3/jboss/dvmka433/vwi-development1-rms3/AppLog/', wsLog: '/logs/vwi/development3/jboss/dvmka433/vwi-development1-rms3/WebSrv/AppLog/', boLog: '/logs/vwi/development2/jboss/dvmki811/vwi-development2-rmsmodern/RearchLog/', foHost: 'dvmka433.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '9280', boPort: '9280', esPort: '13280', displayName: 'VWI DEV3', tns: ['PRTD301=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(COMMUNITY=TCP.WORLD)(PROTOCOL=TCP)(HOST=DREAA658.DEV.SPRINT.COM)(PORT=1525)))(CONNECT_DATA=(SERVICE_NAME=PRTD301)))'] },
  { db: 'PRTD401', foLog:'/logs/vwi/development4/jboss/dvmka433/vwi-development1-rms4/AppLog/', wsLog: '/logs/vwi/development4/jboss/dvmka433/vwi-development1-rms4/WebSrv/AppLog/', boLog: '/logs/vwi/development3/jboss/dvmki811/vwi-development3-rmsmodern/RearchLog/', foHost: 'dvmka433.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '9380', boPort: '9380', esPort: '13380', displayName: 'VWI DEV4', tns: ['PRTD401=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(COMMUNITY=TCP.WORLD)(PROTOCOL=TCP)(HOST=DREAA658.DEV.SPRINT.COM)(PORT=1525)))(CONNECT_DATA=(SERVICE_NAME=PRTD401)))'] },
  { db: 'PRTD501', foLog:'/logs/vwi/development5/jboss/dvmka433/vwi-development1-rms5/AppLog/', wsLog: '/logs/vwi/development5/jboss/dvmka433/vwi-development1-rms5/WebSrv/AppLog/', boLog: '/logs/vwi/development4/jboss/dvmki811/vwi-development4-rmsmodern/RearchLog/', foHost: 'dvmka433.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '9480', boPort: '9480', esPort: '13480', displayName: 'VWI DEV5', tns: ['PRTD501=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(COMMUNITY=TCP.WORLD)(PROTOCOL=TCP)(HOST=DREAA658.DEV.SPRINT.COM)(PORT=1525)))(CONNECT_DATA=(SERVICE_NAME=PRTD501)))'] },
  { db: 'PRTD601', foLog:'/logs/vwi/development6/jboss/dvmka433/vwi-development1-rms6/AppLog/', wsLog: '/logs/vwi/development6/jboss/dvmka433/vwi-development1-rms6/WebSrv/AppLog/', boLog: '/logs/vwi/development5/jboss/dvmki811/vwi-development5-rmsmodern/RearchLog/', foHost: 'dvmka433.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki811.dev.sprint.com', foPort: '10080', boPort: '9580', esPort: '13580', displayName: 'VWI DEV6', tns: ['PRTD601=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=dreaa658.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=PRTD601)))'] },
  { db: 'PRTD701', foLog:'/logs/vwi/development7/jboss/dvmka433/vwi-development1-rms7/AppLog/', wsLog: '/logs/vwi/development7/jboss/dvmka433/vwi-development1-rms7/WebSrv/AppLog/', boLog: '/logs/vwi/development6/jboss/dvmki811/vwi-development6-rmsmodern/RearchLog/', foHost: 'dvmka433.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki811.dev.sprint.com', foPort: '10180', boPort: '9680', esPort: '13680', displayName: 'VWI DEV7', tns: ['PRTD701=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=dreaa658.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=PRTD701)))'] },
  { db: 'PRTD801', foLog:'/logs/vwi/development8/jboss/dvmka433/vwi-development1-rms8/AppLog/', wsLog: '/logs/vwi/development8/jboss/dvmka433/vwi-development1-rms8/WebSrv/AppLog/', boLog: '/logs/vwi/development7/jboss/dvmki811/vwi-development7-rmsmodern/RearchLog/', foHost: 'dvmka433.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki811.dev.sprint.com', foPort: '10280', boPort: '9780', esPort: '13780', displayName: 'VWI DEV8', tns: ['PRTD801=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=dreaa658.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=PRTD801)))'] },
  { db: 'PRTD901', foLog:'/logs/vwi/development9/jboss/dvmka433/vwi-development1-rms9/AppLog/', wsLog: '/logs/vwi/development9/jboss/dvmka433/vwi-development1-rms9/WebSrv/AppLog/', boLog: '/logs/vwi/development8/jboss/dvmki811/vwi-development8-rmsmodern/RearchLog/', foHost: 'dvmka433.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki811.dev.sprint.com', foPort: '10380', boPort: '9880', esPort: '13880', displayName: 'VWI DEV9', tns: ['PRTD901=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=dreaa658.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=PRTD901)))'] },
  { db: 'PRTD001', foLog:'/logs/vwi/development10/jboss/dvmka433/vwi-development1-rms10/AppLog/', wsLog: '/logs/vwi/development10/jboss/dvmka433/vwi-development1-rms10/WebSrv/AppLog/', boLog: '/logs/vwi/development9/jboss/dvmki811/vwi-development9-rmsmodern/RearchLog/', foHost: 'dvmka433.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki811.dev.sprint.com', foPort: '10480', boPort: '9980', esPort: '13980', displayName: 'VWI DEV10', tns: ['PRTD001=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=dreaa658.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=PRTD001)))'] },
  { db: 'RSKD101', foLog:'/logs/lfo/development1/jboss/dvmkf506/lfo-development1-rms1/AppLog/', wsLog: '/logs/lfo/development1/jboss/dvmkf506/lfo-development1-rms1/WebSrv/AppLog', boLog: '/logs/lfo/development0/jboss/dvmki811/lfo-development0-rmsmodern/RearchLog/', jmLog: '/logs/ws2/development1/jboss/dvmki489/ws2-development1-rcdws/rhs/production/apps/', foHost: 'dvmkf506.dev.sprint.com', jmHost: 'dvmki489.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8080', boPort: '10080', jmPort: '8180', esPort: '14080', displayName: 'LFO DEV1', tns: ['RSKD101=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=dreaa958.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=RSKD101)))', 'CNTD101=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=dreab485.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTD1APPS)))'] },
  { db: 'RSKD201', foLog:'/logs/lfo/development2/jboss/dvmkf506/lfo-development2-rms2/AppLog', wsLog: '/logs/lfo/development2/jboss/dvmkf506/lfo-development2-rms2/WebSrv/AppLog', boLog: '/logs/lfo/development1/jboss/dvmki811/lfo-development1-rmsmodern/RearchLog/', jmLog: '/logs/ws2/development2/jboss/dvmki489/ws2-development2-rcdws/rhs/production/apps/', foHost: 'dvmkf506.dev.sprint.com', jmHost: 'dvmki489.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8180', boPort: '10180', jmPort: '8280', esPort: '14180', displayName: 'LFO DEV2', tns: ['RSKD201=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=dreaa958.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=RSKD201)))', 'CNTD201=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=dreab485.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTD2APPS)))'] },
  { db: 'RSKD301', foLog:'/logs/lfo/development3/jboss/dvmkf506/lfo-development3-rms3/AppLog', wsLog: '/logs/lfo/development3/jboss/dvmkf506/lfo-development3-rms3/WebSrv/AppLog', boLog: '/logs/lfo/development2/jboss/dvmki811/lfo-development2-rmsmodern/RearchLog/', jmLog: '/logs/ws2/development3/jboss/dvmki489/ws2-development3-rcdws/rhs/production/apps/', foHost: 'dvmkf506.dev.sprint.com', jmHost: 'dvmki489.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8280', boPort: '10280', jmPort: '8380', esPort: '14280', displayName: 'LFO DEV3', tns: ['RSKD301=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=dreaa958.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=RSKD301)))', 'CNTD301=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=dreab485.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTD3APPS)))'] },
  { db: 'RSKD401', foLog:'/logs/lfo/development4/jboss/dvmkf506/lfo-development4-rms4/AppLog', wsLog: '/logs/lfo/development4/jboss/dvmkf506/lfo-development4-rms4/WebSrv/AppLog', boLog: '/logs/lfo/development3/jboss/dvmki811/lfo-development3-rmsmodern/RearchLog/', jmLog: '/logs/ws2/development4/jboss/dvmki489/ws2-development4-rcdws/rhs/production/apps/', foHost: 'dvmkf506.dev.sprint.com', jmHost: 'dvmki489.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8380', boPort: '10380', jmPort: '8480', esPort: '14380', displayName: 'LFO DEV4', tns: ['RSKD401=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=dreaa958.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=RSKD401)))', 'CNTD401=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=dreab485.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTD4APPS)))'] },
  { db: 'RSKD501', foLog:'/logs/lfo/development5/jboss/dvmkf506/lfo-development5-rms5/AppLog', wsLog: '/logs/lfo/development5/jboss/dvmkf506/lfo-development5-rms5/WebSrv/AppLog', boLog: '/logs/lfo/development4/jboss/dvmki811/lfo-development4-rmsmodern/RearchLog/', jmLog: '/logs/ws2/development5/jboss/dvmki489/ws2-development5-rcdws/rhs/production/apps/', foHost: 'dvmkf506.dev.sprint.com', jmHost: 'dvmki489.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8480', boPort: '10480', jmPort: '8580', esPort: '14480', displayName: 'LFO DEV5', tns: ['RSKD501=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=dreaa958.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=RSKD501)))', 'CNTD501=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=dreab485.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTD5APPS)))'] },
  { db: 'RSKD601', foLog:'/logs/lfo/development6/jboss/dvmkf506/lfo-development6-rms6/AppLog', wsLog: '/logs/lfo/development6/jboss/dvmkf506/lfo-development6-rms6/WebSrv/AppLog', boLog: '/logs/lfo/development5/jboss/dvmki811/lfo-development5-rmsmodern/RearchLog/', jmLog: '/logs/ws2/development6/jboss/dvmki489/ws2-development6-rcdws/rhs/production/apps/', foHost: 'dvmkf506.dev.sprint.com', jmHost: 'dvmki489.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8580', boPort: '10580', jmPort: '8680', esPort: '14580', displayName: 'LFO DEV6', tns: ['RSKD601=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=dreaa958.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=RSKD601)))', 'CNTD601=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=dreab485.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTD6APPS)))'] },
  { db: 'RSKD701', foLog:'/logs/lfo/development7/jboss/dvmkf506/lfo-development7-rms7/AppLog', wsLog: '/logs/lfo/development7/jboss/dvmkf506/lfo-development7-rms7/WebSrv/AppLog', boLog: '/logs/lfo/development6/jboss/dvmki811/lfo-development6-rmsmodern/RearchLog/', jmLog: '/logs/ws2/development7/jboss/dvmki489/ws2-development7-rcdws/rhs/production/apps/', foHost: 'dvmkf506.dev.sprint.com', jmHost: 'dvmki489.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8680', boPort: '10680', jmPort: '8780', esPort: '14680', displayName: 'LFO DEV7', tns: ['RSKD701=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=dreaa958.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=RSKD701)))', 'CNTD701=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=dreab485.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTD7APPS)))'] },
  { db: 'RSKD801', foLog:'/logs/lfo/development8/jboss/dvmkf506/lfo-development8-rms8/AppLog', wsLog: '/logs/lfo/development8/jboss/dvmkf506/lfo-development8-rms8/WebSrv/AppLog', boLog: '/logs/lfo/development7/jboss/dvmki811/lfo-development7-rmsmodern/RearchLog/', jmLog: '/logs/ws2/development8/jboss/dvmki489/ws2-development8-rcdws/rhs/production/apps/', foHost: 'dvmkf506.dev.sprint.com', jmHost: 'dvmki489.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8780', boPort: '10780', jmPort: '8880', esPort: '14780', displayName: 'LFO DEV8', tns: ['RSKD801=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=dreaa958.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=RSKD801)))', 'CNTD801=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=dreab485.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTD8APPS)))'] },
  { db: 'RSKD901', foLog:'/logs/lfo/development9/jboss/dvmkf506/lfo-development9-rms9/AppLog', wsLog: '/logs/lfo/development9/jboss/dvmkf506/lfo-development9-rms9/WebSrv/AppLog', boLog: '/logs/lfo/development8/jboss/dvmki811/lfo-development8-rmsmodern/RearchLog/', jmLog: '/logs/ws2/development9/jboss/dvmki489/ws2-development9-rcdws/rhs/production/apps/', foHost: 'dvmkf506.dev.sprint.com', jmHost: 'dvmki489.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8880', boPort: '10880', jmPort: '8980', esPort: '14880', displayName: 'LFO DEV9', tns: ['RSKD901=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=dreaa958.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=RSKD901)))', 'CNTD901=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=dreab485.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTD9APPS)))'] },
  { db: 'RSKD001', foLog:'/logs/lfo/development10/jboss/dvmkf506/lfo-development10-rms10/AppLog', wsLog: '/logs/lfo/development10/jboss/dvmkf506/lfo-development10-rms10/WebSrv/AppLog', boLog: '/logs/lfo/development9/jboss/dvmki811/lfo-development9-rmsmodern/RearchLog/', jmLog: '/logs/ws2/development10/jboss/dvmki489/ws2-development10-rcdws/rhs/production/apps/', foHost: 'dvmkf506.dev.sprint.com', jmHost: 'dvmki489.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8980', boPort: '10980', jmPort: '9080', esPort: '14980', displayName: 'LFO DEV10', tns: ['RSKD001=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=dreaa958.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=RSKD001)))', 'CNTD001=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=dreab485.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTD0APPS)))'] },
  { db: 'TELD101', foLog:'/logs/rai/development0/jboss/dvmkd625/rai-development0-rms1/AppLog/', wsLog: '/logs/rai/development0/jboss/dvmkd625/rai-development0-rms1/WebSrv/AppLog/', boLog: '/logs/rai/development0/jboss/dvmki811/rai-development0-rmsmodern/RearchLog/', foHost: 'dvmkd625.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8080', boPort: '11080', esPort: '15080', displayName: 'RAI DEV1', tns: ['TELD101=(DESCRIPTION=(ADDRESS=(COMMUNITY=TCP.WORLD)(PROTOCOL=TCP)(HOST=DREAA658.DEV.SPRINT.COM)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=TELD101)))'] },
  { db: 'TELD201', foLog:'/logs/rai/development1/jboss/dvmkd625/rai-development1-rms1/AppLog/', wsLog: '/logs/rai/development1/jboss/dvmkd625/rai-development1-rms1/WebSrv/AppLog/', boLog: '/logs/rai/development1/jboss/dvmki811/rai-development1-rmsmodern/RearchLog/', foHost: 'dvmkd625.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8180', boPort: '11180', esPort: '15180', displayName: 'RAI DEV2', tns: ['TELD201=(DESCRIPTION=(ADDRESS=(COMMUNITY=TCP.WORLD)(PROTOCOL=TCP)(HOST=DREAA658.DEV.SPRINT.COM)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=TELD201)))'] },
  { db: 'TELD301', foLog:'/logs/rai/development2/jboss/dvmkd625/rai-development2-rms1/AppLog/', wsLog: '/logs/rai/development2/jboss/dvmkd625/rai-development2-rms1/WebSrv/AppLog/', boLog: '/logs/rai/development2/jboss/dvmki811/rai-development2-rmsmodern/RearchLog/', foHost: 'dvmkd625.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8280', boPort: '11280', esPort: '15280', displayName: 'RAI DEV3', tns: ['TELD301=(DESCRIPTION=(ADDRESS=(COMMUNITY=TCP.WORLD)(PROTOCOL=TCP)(HOST=DREAA658.DEV.SPRINT.COM)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=TELD301)))'] },
  { db: 'TELD401', foLog:'/logs/rai/development3/jboss/dvmkd625/rai-development3-rms1/AppLog/', wsLog: '/logs/rai/development3/jboss/dvmkd625/rai-development3-rms1/WebSrv/AppLog/', boLog: '/logs/rai/development3/jboss/dvmki811/rai-development3-rmsmodern/RearchLog/', foHost: 'dvmkd625.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8380', boPort: '11380', esPort: '15380', displayName: 'RAI DEV4', tns: ['TELD401=(DESCRIPTION=(ADDRESS=(COMMUNITY=TCP.WORLD)(PROTOCOL=TCP)(HOST=DREAA658.DEV.SPRINT.COM)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=TELD401)))'] },
  { db: 'TELD501', foLog:'/logs/rai/development4/jboss/dvmkd625/rai-development4-rms1/AppLog/', wsLog: '/logs/rai/development4/jboss/dvmkd625/rai-development4-rms1/WebSrv/AppLog/', boLog: '/logs/rai/development4/jboss/dvmki811/rai-development4-rmsmodern/RearchLog/', foHost: 'dvmkd625.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8480', boPort: '11480', esPort: '15480', displayName: 'RAI DEV5', tns: ['TELD501=(DESCRIPTION=(ADDRESS=(COMMUNITY=TCP.WORLD)(PROTOCOL=TCP)(HOST=DREAA658.DEV.SPRINT.COM)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=TELD501)))'] },
  { db: 'TELD601', foLog:'/logs/rai/development5/jboss/dvmkd625/rai-development5-rms1/AppLog/', wsLog: '/logs/rai/development5/jboss/dvmkd625/rai-development5-rms1/WebSrv/AppLog/', boLog: '/logs/rai/development5/jboss/dvmki811/rai-development5-rmsmodern/RearchLog/', foHost: 'dvmkd625.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8580', boPort: '11580', esPort: '15580', displayName: 'RAI DEV6', tns: ['TELD601=(DESCRIPTION=(ADDRESS=(COMMUNITY=TCP.WORLD)(PROTOCOL=TCP)(HOST=DREAA658.DEV.SPRINT.COM)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=TELD601)))'] },
  { db: 'TELD701', foLog:'/logs/rai/development6/jboss/dvmkd625/rai-development6-rms1/AppLog/', wsLog: '/logs/rai/development6/jboss/dvmkd625/rai-development6-rms1/WebSrv/AppLog/', boLog: '/logs/rai/development6/jboss/dvmki811/rai-development6-rmsmodern/RearchLog/', foHost: 'dvmkd625.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8680', boPort: '11680', esPort: '15680', displayName: 'RAI DEV7', tns: ['TELD701=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=dreaa658.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=TELD701)))'] },
  { db: 'TELD801', foLog:'/logs/rai/development7/jboss/dvmkd625/rai-development7-rms1/AppLog/', wsLog: '/logs/rai/development7/jboss/dvmkd625/rai-development7-rms1/WebSrv/AppLog/', boLog: '/logs/rai/development7/jboss/dvmki811/rai-development7-rmsmodern/RearchLog/', foHost: 'dvmkd625.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8780', boPort: '11780', esPort: '15780', displayName: 'RAI DEV8', tns: ['TELD801=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=dreaa658.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=TELD801)))'] },
  { db: 'TELD901', foLog:'/logs/rai/development8/jboss/dvmkd625/rai-development8-rms1/AppLog/', wsLog: '/logs/rai/development8/jboss/dvmkd625/rai-development8-rms1/WebSrv/AppLog/', boLog: '/logs/rai/development8/jboss/dvmki811/rai-development8-rmsmodern/RearchLog/', foHost: 'dvmkd625.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8880', boPort: '11880', esPort: '15880', displayName: 'RAI DEV9', tns: ['TELD901=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=dreaa658.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=TELD901)))'] },
  { db: 'TELD001', foLog:'/logs/rai/development9/jboss/dvmkd625/rai-development9-rms1/AppLog/', wsLog: '/logs/rai/development9/jboss/dvmkd625/rai-development9-rms1/WebSrv/AppLog/', boLog: '/logs/rai/development9/jboss/dvmki811/rai-development9-rmsmodern/RearchLog/', foHost: 'dvmkd625.dev.sprint.com', boAppHost: 'dvmki811.dev.sprint.com', boHost: 'dvmki810.dev.sprint.com', foPort: '8980', boPort: '11980', esPort: '15980', displayName: 'RAI DEV10', tns: ['TELD001=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=dreaa658.dev.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=TELD001)))'] },
  { db: 'RMST101', foLog:'/logs/rhs/test1/jboss/tvmkb140/rhs-test1-rms1/AppLog/', wsLog: '/logs/rhs/test1/jboss/tvmkb140/rhs-test1-rms1/WebSrv/AppLog/', boLog: '/logs/rhs/test1/jboss/tvmki885/rhs-test1-rmsmodern/RearchLog/', jmLog: '/logs/ws2/test1/jboss/tvmki492/ws2-test1-rcdws2/rhs/production/apps/', foHost: 'tvmkb140.test.sprint.com', jmHost: 'tvmki492.test.sprint.com', boAppHost: 'tvmki885.test.sprint.com', boHost: 'tvmki883.test.sprint.com', foPort: '8380', boPort: '8280', jmPort: '8280', esPort: '9200', displayName: 'RHS ITE1', tns: ['RMST101=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=TREAA542.TEST.SPRINT.COM)(PORT=1525)))(CONNECT_DATA=(SID=RMST101)))', 'CNTT101=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=treab545.test.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTT101)(FAILOVER_MODE=(TYPE=SELECT)(METHOD=BASIC)(RETRIES=180)(DELAY=5))))'] },
  { db: 'PRTT101', foLog:'/logs/vwi/test1/jboss/tvmkb140/vwi-test1-rms1/AppLog/', wsLog: '/logs/vwi/test1/jboss/tvmkb140/vwi-test1-rms1/WebSrv/AppLog/', boLog: '/logs/vwi/test1/jboss/tvmki885/vwi-test1-rmsmodern/RearchLog/', foHost: 'tvmkb139.test.sprint.com', boAppHost: 'tvmki885.test.sprint.com', boHost: 'tvmki883.test.sprint.com', foPort: '8680', boPort: '8380', esPort: '9230', displayName: 'VWI ITE1', tns: ['PRTT101=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(COMMUNITY=TCP.WORLD)(PROTOCOL=TCP)(HOST=TREAA542.TEST.SPRINT.COM)(PORT=1525)))(CONNECT_DATA=(SID=PRTT101)))'] },
  { db: 'RSKT101', foLog:'/logs/lfo/test1/jboss/tvmkf349/lfo-test1-rms1/AppLog/', wsLog: '/logs/lfo/test1/jboss/tvmkf349/lfo-test1-rms1/WebSrv/AppLog/', boLog: '/logs/lfo/test1/jboss/tvmki885/lfo-test1-rmsmodern/RearchLog/', jmLog: '/logs/ws2/test1/jboss/tvmki492/ws2-test1-rcdws2/rhs/production/apps/', foHost: 'tvmkf349.test.sprint.com', jmHost: 'tvmki492.test.sprint.com', boAppHost: 'tvmki885.test.sprint.com', boHost: 'tvmki883.test.sprint.com', foPort: '8080', boPort: '8080', jmPort: '8180', esPort: '9220', displayName: 'LFO ITE1', tns: ['RSKT101=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=TREAA901.TEST.SPRINT.COM)(PORT=1521))(CONNECT_DATA=(SID=RSKT101)))', 'CNTT101=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=treab545.test.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTT101)(FAILOVER_MODE=(TYPE=SELECT)(METHOD=BASIC)(RETRIES=180)(DELAY=5))))'] },
  { db: 'TELT101', foLog:'/logs/rai/test1/jboss/tvmkd650/rai-test1-rms1/AppLog/', wsLog: '/logs/rai/test1/jboss/tvmkd650/rai-test1-rms1/WebSrv/AppLog/', boLog: '/logs/rai/test1/jboss/tvmki885/rai-test1-rmsmodern/RearchLog/', foHost: 'tvmkd650.test.sprint.com', boAppHost: 'tvmki885.test.sprint.com', boHost: 'tvmki883.test.sprint.com', foPort: '8080', boPort: '8180', esPort: '9210', displayName: 'RAI ITE1', tns: ['TELT101=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=TREAA542.TEST.SPRINT.COM)(PORT=1525))(CONNECT_DATA=(SID=TELT101)))'] },
  { db: 'RMST201', foLog:'/logs/rhs/test2/jboss/tvmkb141/rhs-test2-rms1/AppLog/', wsLog: '/logs/rhs/test2/jboss/tvmkb141/rhs-test2-rms1/WebSrv/AppLog/', boLog: '/logs/rhs/test2/jboss/tvmki886/rhs-test2-rmsmodern1/RearchLog/', jmLog: '/logs/ws2/test2/jboss/tvmki493/ws2-test2-rcdws2/rhs/production/apps/', foHost: 'tvmkb141.test.sprint.com', jmHost: 'tvmki493.test.sprint.com', boAppHost: 'tvmki886.test.sprint.com', boHost: 'tvmki884.test.sprint.com', foPort: '8380', boPort: '8280', jmPort: '8280', esPort: '9200', displayName: 'RHS ITE2', tns: ['RMST201=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(COMMUNITY=TCP)(PROTOCOL=TCP)(HOST=TREAA543.TEST.SPRINT.COM)(PORT=1521)))(CONNECT_DATA=(SID=RMST201)))', 'CNTT201=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=treab546.test.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTT201)(FAILOVER_MODE=(TYPE=SELECT)(METHOD=BASIC)(RETRIES=180)(DELAY=5))))'] },
  { db: 'PRTT201', foLog:'/logs/vwi/test2/jboss/tvmkb141/vwi-test2-rms1/AppLog/', wsLog: '/logs/vwi/test2/jboss/tvmkb141/vwi-test2-rms1/WebSrv/AppLog/', boLog: '/logs/vwi/test2/jboss/tvmki886/vwi-test2-rmsmodern1/RearchLog/', foHost: 'tvmkb141.test.sprint.com', boAppHost: 'tvmki886.test.sprint.com', boHost: 'tvmki884.test.sprint.com', foPort: '8680', boPort: '8380', esPort: '9230', displayName: 'VWI ITE2', tns: ['PRTT201=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(COMMUNITY=TCP)(PROTOCOL=TCP)(HOST=TREAA543.TEST.SPRINT.COM)(PORT=1521)))(CONNECT_DATA=(SID=PRTT201)))'] },
  { db: 'RSKT201', foLog:'/logs/lfo/test2/jboss/tvmkf351/lfo-test2-rms1/AppLog/', wsLog: '/logs/lfo/test2/jboss/tvmkf351/lfo-test2-rms1/WebSrv/AppLog/', boLog: '/logs/lfo/test2/jboss/tvmki886/lfo-test2-rmsmodern1/RearchLog/', jmLog: '/logs/ws2/test2/jboss/tvmki493/ws2-test2-rcdws2/rhs/production/apps/', foHost: 'tvmkf351.test.sprint.com', jmHost: 'tvmki493.test.sprint.com', boAppHost: 'tvmki886.test.sprint.com', boHost: 'tvmki884.test.sprint.com', foPort: '8080', boPort: '8080', jmPort: '8280', esPort: '9220', displayName: 'LFO ITE2', tns: ['RSKT201=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=TREAA902.TEST.SPRINT.COM)(PORT=1521))(CONNECT_DATA=(SID=RSKT201)))', 'CNTT201=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=treab546.test.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTT201)(FAILOVER_MODE=(TYPE=SELECT)(METHOD=BASIC)(RETRIES=180)(DELAY=5))))'] },
  { db: 'TELT201', foLog:'/logs/rai/test2/jboss/tvmkd652/rai-test2-rms1/AppLog/', wsLog: '/logs/rai/test2/jboss/tvmkd652/rai-test2-rms1/WebSrv/AppLog/', boLog: '/logs/rai/test2/jboss/tvmki886/rai-test2-rmsmodern1/RearchLog/', foHost: 'tvmkd652.test.sprint.com', boAppHost: 'tvmki886.test.sprint.com', boHost: 'tvmki884.test.sprint.com', foPort: '8080', boPort: '8180', esPort: '9210', displayName: 'RAI ITE2', tns: ['TELT201=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=TREAA543.TEST.SPRINT.COM)(PORT=1521))(CONNECT_DATA=(SID=TELT201)))'] },
  { db: 'RMST401', foLog:'/logs/rhs/ite3/jboss/tvmkk279/rhs-ite3-rms1/AppLog/', wsLog: '/logs/rhs/ite3/jboss/tvmkk279/rhs-ite3-rms1/WebSrv/AppLog/', boLog: '/logs/rhs/ite3/jboss/tvmkk281/rhs-ite3-rmsmodern1/RearchLog/', jmLog: '/logs/ws2/ite3/jboss/tvmkk287/ws2-ite3-rcdws2/rhs/production/apps/', foHost: 'tvmkk279.test.sprint.com', jmHost: 'tvmkk287.test.sprint.com', boAppHost: 'tvmkk281.test.sprint.com', boHost: 'tvmkk280.test.sprint.com', foPort: '8380', boPort: '8280', jmPort: '8280', esPort: '9200', displayName: 'RHS ITE3', tns: ['RMST401=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=treab744.test.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=RMST401)))', 'CNTT301=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=treab748.test.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTT301)(SID=CNTT301)))'] },
  { db: 'PRTT104', foLog:'/logs/vwi/ite3/jboss/tvmkk279/vwi-ite3-rms1/AppLog/', wsLog: '/logs/vwi/ite3/jboss/tvmkk279/vwi-ite3-rms1/WebSrv/AppLog/', boLog: '/logs/vwi/ite3/jboss/tvmkk281/vwi-ite3-rmsmodern1/RearchLog/', foHost: 'tvmkk279.test.sprint.com', boAppHost: 'tvmkk281.test.sprint.com', boHost: 'tvmkk280.test.sprint.com', foPort: '8680', boPort: '8380', esPort: '9230', displayName: 'VWI ITE3', tns: ['PRTT104=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=treab744.test.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=PRTT104)))'] },
  { db: 'RSKT301', foLog:'/logs/lfo/ite3/jboss/tvmkk285/lfo-ite3-rms1/AppLog/', wsLog: '/logs/lfo/ite3/jboss/tvmkk285/lfo-ite3-rms1/WebSrv/AppLog/', boLog: '/logs/lfo/ite3/jboss/tvmkk281/lfo-ite3-rmsmodern1/RearchLog/', jmLog: '/logs/ws2/ite3/jboss/tvmkk287/ws2-ite3-rcdws2/rhs/production/apps/', foHost: 'tvmkk285.test.sprint.com', jmHost: 'tvmkk287.test.sprint.com', boAppHost: 'tvmkk281.test.sprint.com', boHost: 'tvmkk280.test.sprint.com', foPort: '8080', boPort: '8080', jmPort: '8280', esPort: '9220', displayName: 'LFO ITE3', tns: ['RSKT301=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=treab739.test.sprint.com)(PORT=1521))(CONNECT_DATA=(SID=RSKT301)))', 'CNTT301=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=treab748.test.sprint.com)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=CNTT301)(SID=CNTT301)))'] },
  { db: 'TELT401', foLog:'/logs/rai/ite3/jboss/tvmkk283/rai-ite3-rms1/AppLog/', wsLog: '/logs/rai/ite3/jboss/tvmkk283/rai-ite3-rms1/WebSrv/AppLog/', boLog: '/logs/rai/ite3/jboss/tvmkk281/rai-ite3-rmsmodern1/RearchLog/', foHost: 'tvmkk283.test.sprint.com', boAppHost: 'tvmkk281.test.sprint.com', boHost: 'tvmkk280.test.sprint.com', foPort: '8080', boPort: '8180', esPort: '9210', displayName: 'RAI ITE3', tns: ['TELT401=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=treab744.test.sprint.com)(PORT=1525))(CONNECT_DATA=(SID=TELT401)))'] }
];

const USERS = ['ABABU6', 'ANAIR29', 'CDADDAL1', 'AARPUTA1', 'KPADMAK1'];

const environ = _.find(DB_URL_COMPLEMENT, { 'APPID': 'REL', 'Env': 'PROD' });
const devdb = _.find(DB_DETAILS, 'DEV');
const testdb = _.find(DB_DETAILS, 'TEST');

const findBaseUrl = () => {
  if (window.location.host === 'localhost:4200') {
    return `http://${environ.URL}:${environ.PORT}/`;
  }
  return `http://${window.location.host}/`;
};

export const environment = {
  production: true,
  baseRestUrl: findBaseUrl(),
  devDB: devdb.DEV,
  testDB: testdb.TEST,
  urlDetails: URL_DETAILS,
  serverDetails: SERVER_DETAILS,
  userList: USERS
};
//ng build --base-href /LinkCorner/ --prod
//ng serve --hmr